name = "OptimizationCallbacks"
uuid = "65fa8838-c146-46ed-aad7-5f6b0eb2af66"
authors = ["Johanni Brea <jbrea@users.noreply.github.com>"]
version = "0.1.0"

[deps]
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
ConcreteStructs = "0.2"
JLD2 = "0.5, 0.6"
Printf = "1"
julia = "1.9"

[extras]

[targets]
